# Generated by Django 2.2.6 on 2020-09-09 18:58

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeMachines',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('SKU', models.CharField(max_length=255)),
                ('model_model', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=255)),
                ('water_line_compatible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CoffeePods',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('SKU', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=255)),
                ('coffee_flavor', models.CharField(max_length=255)),
                ('pack_size', models.CharField(max_length=255)),
            ],
        ),
    ]
