# Generated by Django 2.2.6 on 2020-09-10 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffeemachines',
            old_name='model_model',
            new_name='model_type',
        ),
    ]
